### ISSUE TITLE
DPI scaling wrong on Mac

### ISSUE THREAD

**Issue by leontepe** [linebender/xilem#11]
As discussed on Zulip.

<img width="191" alt="Screenshot-2022-11-26-at-15 10 58" src="https://user-images.githubusercontent.com/27787342/204098139-b2272079-6a91-4cad-8344-95ed607847f7.png">

**Comment by raphlinus** [comment]
I expect this will be fixed by https://github.com/linebender/glazier/pull/37.

**Comment by leontepe** [comment]
Fixed, closing.

<img width="191" alt="Screenshot 2022-11-27 at 10 50 50" src="https://user-images.githubusercontent.com/27787342/204129055-eb517170-87ef-4dfc-9061-dde5365d8791.png">
