### ISSUE TITLE
`examples/hello.rs` has no text, just bare buttons?

### ISSUE THREAD

**Issue by Infinoid** [linebender/xilem#120]
I'm trying xilem for the first time.  It's experimental, so I don't really know what to expect.  So I'll ask:

I tried running the `examples/hello.rs` example.  Here is what I saw when it ran:

![image](https://github.com/linebender/xilem/assets/50254/d99a903f-c324-4594-95c0-e5f2b037b354)

The buttons have no text.  Is this expected?  Is it the same thing everyone else sees?  Did I do it wrong?

I wonder if I'm missing a font or something.  I don't see any errors about that.  Or maybe it's some weird dark mode theme thing?  Do themes even exist yet?  Like I said, I don't really know what to expect.

<details>
<summary>steps to reproduce</summary>

1. rustup update
2. mkdir xilem-hello
3. cd xilem-hello
4. cargo init
5. wget https://raw.githubusercontent.com/linebender/xilem/main/examples/hello.rs -O src/main.rs
6. cargo add --git https://github.com/linebender/xilem xilem
7. cargo run
8. see the lack of text
9. close the window

[Here's the Cargo.toml I ended up with](https://gist.githubusercontent.com/Infinoid/937a099f4b6f6954736d3d196c34333f/raw/6ec45b510b8376885d4a2a71153d2299cb23b38b/Cargo.toml), after running the above steps.
</details>

[Log of `cargo run` building and running it](https://gist.githubusercontent.com/Infinoid/937a099f4b6f6954736d3d196c34333f/raw/6ec45b510b8376885d4a2a71153d2299cb23b38b/cargo-run.plain.txt).

<details>
<summary>my system details</summary>

## Rust tool versions

rustup 1.26.0 (5af9b9484 2023-04-05)
rustc 1.71.1 (eb26296b5 2023-08-03)
cargo 1.71.1 (7f1d04c00 2023-07-29)

## OS & packages

Linux kernel 6.1.42.
Debian 12 (bookworm).

```
||/ Name                      Version              Architecture Description
+++-=========================-====================-============-=========================================================
ii  libxcb1:amd64             1.15-1               amd64        X C Binding
ii  libxkbcommon-x11-0:amd64  1.5.0-1              amd64        library to create keymaps with the XKB X11 protocol
ii  nvidia-kernel-dkms        525.125.06-1~deb12u1 amd64        NVIDIA binary kernel module DKMS source
ii  xfce4                     4.18                 all          Meta-package for the Xfce Lightweight Desktop Environment
ii  xserver-xorg              1:7.7+23             amd64        X.Org X server
ii  xserver-xorg-video-nvidia 525.125.06-1~deb12u1 amd64        NVIDIA binary Xorg driver
```

## Hardware

GPU:

```
43:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3080 12GB] (rev a1)
43:00.1 Audio device: NVIDIA Corporation GA102 High Definition Audio Controller (rev a1)
```

I am using a multi-monitor setup via `xrandr`.   Here's a summary:
```
% xrandr --listactivemonitors
Monitors: 3
 0: +*DP-2 3840/600x2160/340+3840+0  DP-2
 1: +DP-4 3840/600x2160/340+0+0  DP-4
 2: +DP-0 3840/600x2160/340+7680+0  DP-0
```

`xdpyinfo` says this:
```
screen #0:
  dimensions:    11520x2160 pixels (1806x338 millimeters)
  resolution:    162x162 dots per inch
  depths (7):    24, 1, 4, 8, 15, 16, 32
```

</details>

**Comment by raphlinus** [comment]
This is a dup of #32, and a fix (rendering CFF fonts) is in the works. Not sure exactly when it will land, though.

**Comment by Infinoid** [comment]
Ok, thanks.  Glad to know I didn't break something.  I'll follow that issue.

**Comment by dfrg** [comment]
CFF fonts should be supported now. @Infinoid please let us know if it’s still broken for you.

**Comment by Infinoid** [comment]
@dfrg Yes, the buttons now have text.  The font choice is interesting, but it's a definite improvement.

![image](https://github.com/linebender/xilem/assets/50254/a7a80988-64a4-4ab4-8e93-1ee3984fdb4f)

Thanks for the update!
