### ISSUE TITLE
Add  John Skottis' architecture overview to the documentation

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/xilem#151]
John has written [a pretty good overview of Xilem's architecture](https://gist.github.com/giannissc/ed924d5773caefc5311fb6d0aee1f502); it's maybe a bit too long to serve as an ARCHITECTURE.md file, but we could add it in a doc folder and link to it from the eventual ARCHITECTURE.md file.

Also: we need an ARCHITECTURE.md file.

**Comment by DJMcNab** [comment]
Closed by #277
