### ISSUE TITLE
Xilem on winit

### ISSUE THREAD

**Issue by raphlinus** [linebender/xilem#163]
At office hours on 2024-01-18 ([notes doc])https://docs.google.com/document/d/1ws5W0tmrs7elNDo2cGbKoDJeUHYuUsQS7Gl3SS5cx0Q/edit)) we agreed to join forces with winit, especially for bringup on Android. A really good step in that direction will be to switch the current Xilem widget tree to winit.

The technical work should be fairly straightforward. We are already using winit for the main Vello demos (see the with_winit subdir). One potentially tricky aspect is the wasm back-end, as we currently have a hard dep on tokio. I suggest we defer that, as there are a number of infrastructure changes in flight (moving the work to the Masonry crate, also dealing with dynamic buffer size in Vello).

This would be a great issue for someone to become more involved with the project.

**Comment by xorgy** [comment]
#176 Contains my current work on this. The first pass at this is Glazier-compatible (Glazier types in events are preserved, even if no value is added).
