### ISSUE TITLE
An idea about UI

### ISSUE THREAD

**Issue by charming-madoka-kaname** [linebender/xilem#194]
I had noticed in Rust UI the things are... messy? Of course, I don't know the right word, but all of us understand the center of topic.

Any months ago, I had seen a Python library; named Kivy. This library was awesome because they got the work done separating UI concerns from logic concerns. How? They add some files *.kv, where I saw structure and in this idea bindings are automatized.

I believe Rust can benefit from this approach. Would you like take a look, please?

**Comment by PoignardAzur** [comment]
Closing this issue for now. In general, this kind of discussion goes a lot further as a thread on our zulip server:

https://xi.zulipchat.com/#narrow/stream/422907-rust-ui

Issues work better when you have a specific actionable item you want to change.
