### ISSUE TITLE
Remove dependency on smallvec and set MSRV of 1.75

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/xilem#253]
Smallvec in Masonry was always intended to be a placeholder until return-position impl Trait was stabilized. Well, now it's stable, it's been stable for a year, we should use it.

Methods that return `Smallvec<T>` should instead return `impl Iterator<Item = T>`. The MSRV of Masonry and xilem_masonry should be set to reflect that.

EDIT: Complicated by the fact that we need Widget to be dyn-safe. Might need to be postponed.

**Comment by Philipp-M** [comment]
I want to note, that RPITIT prevents trait-objects (more specifically `Box<dyn Widget>` is not possible then). It's also generally [discouraged](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#where-the-gaps-lie) for public APIs (see also https://github.com/rust-lang/rfcs/pull/3425#issuecomment-1533873712).

**Comment by PoignardAzur** [comment]
> I want to note, that RPITIT prevents trait-objects (more specifically Box<dyn Widget> is not possible then).

How so?

**Comment by Philipp-M** [comment]
> How so?

See https://doc.rust-lang.org/beta/reference/items/traits.html#object-safety

> mostly confident we're never going to bump into the problems that link mentions

Probably, main issue is mostly trait object safety for `Widget` AFAICS.

I'm not yet that confident in the masonry codebase, but is it even necessary to have `children` in the `Widget` trait? (I.e. have it instead on the concrete widget types)?

**Comment by PoignardAzur** [comment]
Oh, right, the Widget trait is the one that returns children. Well, there would be ways around that, but I do agree that complicates things a bit.

> I'm not yet that confident in the masonry codebase, but is it even necessary to have `children` in the `Widget` trait? (I.e. have it instead on the concrete widget types)?

Yup. This means that the framework can eg take a position and return a reference to the Widget at that position without having to write code in WidgetPod. It's also useful for debugging, building the accessibility tree, and in the future the event system will rely on it a lot more.

Having `children()` on the `Widget` trait is a core design element.

**Comment by PoignardAzur** [comment]
Closing this for now, since we do want the Widget trait to remain dyn-safe.
