### ISSUE TITLE
Can this support states of child components?

### ISSUE THREAD

**Issue by matthunz** [linebender/xilem#29]
For example, if a button has a boolean state of `pressed` and I have a lot of them, do they have to become part of the global state now?

If so I think some way of combining the data tree with the widget tree could make this more flexible

**Comment by matthunz** [comment]
`It would be very limiting to have a single “app state” type throughout the application, and require all callbacks to express their state mutations in terms of that global type. So we won’t do that.`

Nevermind this was explained in the blog post!

**Comment by matthunz** [comment]
Actually the more I read into it it seems a global state is required, the `Adapt` node will just help to map it.

My concern is that for components like buttons we would now need to track their state globally. For example a button that tracks when it's hovered may have internal state to change it's background color.

**Comment by matthunz** [comment]
If that's the case we could an 'IntoView' trait and have a  'Button' be in the global state so that we can can call 'into_view' on it

**Comment by Zoxc** [comment]
Both views and widgets can have internal state. There's also the `UseState` view which can create internal state without a custom view implementation, but it's a bit more awkward due to its `Arc` requirement.
