### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Diggsey** [linebender/xilem#30]
Hi - I read the blog post and am interested in the concept. I was wondering if you had some kind of roadmap? Things look sufficiently in flux that I suspect you are not ready to accept random contributions at this time?

**Comment by nilsmartel** [comment]
I think most of the organisation happens in Zulip at the moment.
xi.zulipchat.com/

I'd imagine there are more in-depth resources about this

**Comment by xStrom** [comment]
This same roadmap / contributions question [came up recently on Zulip](https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/.E2.9C.94.20Roadmap.20for.20contributors).

As for random contributions, we may accept them, but its risky. If its a small thing you can just go ahead and do it. However for significant work it can save time to discuss your plans briefly before actually doing it. Again Zulip is a good spot for that but you can also create an issue here on GitHub for discussion.

**Comment by DJMcNab** [comment]
We now have a published roadmap for the near term at: https://linebender.org/blog/roadmap-may-2024/
And with a longer time horizon at: https://linebender.org/wiki/long-term-roadmap/

Thanks for your interest. We're currently not set up with easy tasks to accept contributions towards, but if you find something you want to work on, please let us know on the Zulip and we can try and guide you
