### ISSUE TITLE
Masonry: Request layout does not implicitly start a redraw

### ISSUE THREAD

**Issue by DJMcNab** [linebender/xilem#301]
If, when responding to an event, you change state which will be updated in layout, the way you have to handle that is:
```
ctx.request_layout();
ctx.request_paint();
```
e.g.
https://github.com/linebender/xilem/blob/aaeeadbbd75a3984e404c2d545fcf7e8abaa72f0/crates/masonry/src/widget/textbox.rs#L182-L184

Otherwise, the update does not actually get drawn. This is not very ergonomic, and is a significant footgun in the masonry layer that this does not happen. We need to find a solution here. That might just be that `request_layout` also requests a paint; this should be at the right level in the passes

**Comment by Philipp-M** [comment]
Maybe we can request a paint, when the layout pass needs it? So that when layout doesn't change anything that requires a repaint, we can save a paint pass? But maybe this is also too much of a footgun, and a layout request should just imply a paint request.

**Comment by DJMcNab** [comment]
That's a subtly different question, I think. This is about scheduling a layout to actually happen. Currently, that is the next time a paint is requested, because only needs_paint sends Winit a redraw requested command - handling that is when the layout/paint pass actually happens

**Comment by Philipp-M** [comment]
Yeah probably a subtly different question. I do think though, it's not necessarily a footgun when we have a good testsuite. One just needs to remember what may really have changed and request all the passes that are necessary for that. And when one of the passes requires a further pass, that should be reflected in that pass.

I just checked, currently at least a layout pass implies a repaint:

https://github.com/linebender/xilem/blob/aaeeadbbd75a3984e404c2d545fcf7e8abaa72f0/crates/masonry/src/widget/widget_pod.rs#L848-L849

But when checking e.g.

https://github.com/linebender/xilem/blob/aaeeadbbd75a3984e404c2d545fcf7e8abaa72f0/crates/masonry/src/widget/image.rs#L59-L64

this could indeed be a footgun, when the `TODO` would be resolved and the image dimensions haven't changed in a new `ImageBuf`...
