### ISSUE TITLE
The memory usage is relatively high, and there will be a brief white screen when starting.

### ISSUE THREAD

**Issue by WZY1999428** [linebender/xilem#319]
I used the code of git clone to run a simple example. The memory usage reached more than 200 m, and there was a white screen for one second after startup.
![1716858114330](https://github.com/linebender/xilem/assets/48763949/6396b77f-d190-4ea3-9711-42d4581f5948)
![1716858158945](https://github.com/linebender/xilem/assets/48763949/59f82fb2-ec5c-42d1-a68d-43c0260806bc)

**Comment by DJMcNab** [comment]
The high memory usage is somewhat expected. This is related to linebender/vello#366, where we allocate buffers of a fixed size, and these sized are not tunable. This is among my priorities, although there are also projects I will be working on.

The starting white screen is probably related to linebender/vello#485 and other related issues, where shader compilation is taking a long time. linebender/vello#575 will almost certainly help resolve this, and we're working to land that in Xilem soon (we need to do a Vello release first)

**Comment by WZY1999428** [comment]
I'm not sure if this is the issue, I saw a similar question so I closed it, should I keep it open?

**Comment by WZY1999428** [comment]
I think it should be that the startup speed is now half faster than before

**Comment by WZY1999428** [comment]
> 你能否确认#381是否对此有影响（特别是启动时的白屏）？

I think it should be that the startup speed is now half faster than before
