### ISSUE TITLE
base demo fails to draw text on button.

### ISSUE THREAD

**Issue by cbondurant** [linebender/xilem#32]
I cloned the repository and attempted to run the default main application as a sanity check for myself, however my screen is presented with an empty button. 

The only notable thing I could deduce while poking around the source code, is that the `if let Some(fragment)` statement on `text.rs:40` always fails, and nothing is ever appended to builder.  Could it be a failure in default font discovery?

My system is Linux Mint, running x11 with i3 as my WM and Plasma as my DE.

**Comment by dfrg** [comment]
Thanks for the detailed report. The font fallback support on Linux is currently a stopgap that works in many cases but not all. I am working on a replacement for this that is showing promising results on Linux but progress is slow due to focus on higher priority items at the moment so I can’t give any time estimate for completion.

**Comment by bluenote10** [comment]
@dfrg What exactly is the status of this? I can see that parley has received a commit https://github.com/dfrg/parley/commit/a885c3c659fa9fd81f04bc07139421f24ce7ba68 in February addressing this issue, and Xilem seem to use a later commit, so the fix should be included as far as I can see. However, for me the Xilem example still looks like this:

![image](https://github.com/linebender/xilem/assets/3620703/dcfe731b-64a4-4f4f-b149-212d7a54abeb)

**Comment by dfrg** [comment]
CFF fonts should be working now. Better font fallback is still in progress but I’m trying to schedule some time to work on it soon.

**Comment by cbondurant** [comment]
My platform has changed significantly since I last reported this.
For posterity: I am now running Arch, however I am still utilizing the same x11, i3, plasma setup.

I attempted to run the `to_do_mvc` example and all of the buttons have their appropriate text. So it seems this is likely resolved now!

(While it seems I could close this myself, I do not feel like it would be my place to state this is closed with confidence.)

**Comment by DJMcNab** [comment]
Thanks for your extremely quick reply!
