### ISSUE TITLE
Why not use React & Typescript ? 

### ISSUE THREAD

**Issue by Mistobaan** [linebender/xilem#34]
I think you can have a lot of power if you can implement only a subset of the DOM drawing and have a typescript/js interpreter in RUST that can leverage the xilem primitives.

**Comment by Speykious** [comment]
I may not be the most qualified to answer your question, but given the nature of Xilem, I'm quite shocked that you would even ask such a question.
Have you read the article on Xilem? https://raphlinus.github.io/rust/gui/2022/05/07/ui-architecture.html

Adding a TS/JS interpreter or likewise bundling any kind of web technology would be adding accidental complexity for no additional benefit compared to other GUI frameworks, particularly when it comes to performance.
Besides, the whole point is to be able to make performant, **native** GUIs in Rust without having to rely on third parties, especially the web.

**Comment by Mistobaan** [comment]
A new UI system is born every time there is a new language. GTK, QT, wxPython, the list goes infinite here. I (surprisingly) see the only one that resists the times is HTML + CSS. Learn from thousands of now semi-abandoned projects and don't reinvent the wheel. What sounds interesting to me is a faster GL/HTML-based UI system. Where I can apply #tailwindcss styling and don't have to learn yet another API. just my unsolicited 2 cents, with the only hope that is helpful :)

**Comment by dvc94ch** [comment]
I understand that html/css devs feel scared of learning a real programming language like rust. Especially with GitHub copilot probably producing good enough results that the least competent 10-25% of programmers can be replaced soon.

**Comment by Speykious** [comment]
> Learn from thousands of now semi-abandoned projects and don't reinvent the wheel. What sounds interesting to me is a faster GL/HTML-based UI system. Where I can apply #tailwindcss styling and don't have to learn yet another API. just my unsolicited 2 cents, with the only hope that is helpful :)

If you want something like that, go look at [Dioxus](https://github.com/dioxuslabs/dioxus). Xilem is not what you're looking for.

I would also not put HTML/CSS/JS on a high pedestal just because it resists the times, the reason for that is what @CryZe said above and additionally because it's relatively easy to make. Computers are so fast these days that people tend to not care enough about performance. In my experience, it creates this sub-par experience with software that is really slow, takes a huge amount of memory, with FPS stutters on simple tasks.

Meanwhile any native software I've used that was written in C++ felt immediately less resource and power-hungry with much less input latency.

**Comment by Mistobaan** [comment]
@Speykious Dioxus seems exactly what I imagined this project would be trying to do. 7k stars on Dioxus mean that the idea was pretty good. Thank you a lot for letting me discover Dioxus. The post will be helpful for others that would land to this page with the same idea asking the same question.

> I understand that HTML/CSS devs are scared of learning a programming language like rust. Especially with GitHub copilot probably producing good enough results, the least competent 10-25% of programmers can be replaced soon.
You are a bit off. 80-90% of engineers will be replaced. The entire internet saas world is about to collapse. I need an HTML-like UI because I can prompt it way easier with an LLM than with a new, very low example code. Then ask yourself what happens when a model can generate entire apps in 30 seconds with one framework vs the other.  Let's get back to this thread in 3 years. Right now is just words on a github issue. talk is cheap. show me the code. 

Thank you again for pointing me at Dioxus. Compiling it right now

**Comment by DJMcNab** [comment]
It seems like we've come to the resolution that xilem will not match your vision. I hope you can find a framework which allows you to build what you want to build :)

Another couple of suggestions which match what you are describing:
- [Tauri](https://tauri.app/), which I believe supports React and TypeScript
- [Electron](https://www.electronjs.org/), which also enables creating desktop apps using the DOM

**Comment by xStrom** [comment]
> Learn from thousands of now semi-abandoned projects and don't reinvent the wheel.

Learning from history is certainly what we are doing. To go with your wheel metaphor, we're not building yet another wooden wheel, we're going for a hollow-spoke carbon fibre wheel. Unprecedented performance.

> What sounds interesting to me is a faster GL/HTML-based UI system. Where I can apply #tailwindcss styling and don't have to learn yet another API.

That's fine, but you're quite bold to think that this community that has spent half a decade building custom Rust UI will completely change its direction based on your unwillingness to learn yet another API. It will not happen.

**Comment by Speykious** [comment]
To quote Casey Muratori:
> Saying "reinvent the wheel" is a very misleading statement. [...] The wheel is an amazing invention. It is almost perfect for what it does. When you look at a wheel, it is the thing that perfectly turns dynamic friction into static friction for moving objects. It's something that is so elegant and beautiful, that if you ask me why you would want to reinvent it I would say "of course you don't want to reinvent the wheel, the wheel is amazing". It has worked for thousands of years, it has been unchanged for thousands of years (the concept is the same today as it was when they first made a wheel probably, it makes the exact same stuff physically). Nothing we have developed in the past 30 years of game development is a wheel. If you think Unity is a wheel or Unreal is a wheel, it's just plain shortsided.

Likewise, I would say nothing we have developed in the past 40 years of UI development is a wheel. If you think React is a wheel or HTML/CSS/JS is a wheel, it's just plain shortsided.
