### ISSUE TITLE
Add async support

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/xilem#340]
Xilem used to have support for async workflows. This was implemented in "Xilem classic" in the following commits:

- https://github.com/linebender/xilem/commit/b1e57b02d23313643aa10c2b893a5bdd2571152b
- https://github.com/linebender/xilem/commit/963af1a59873ede0999dcdf603dd3b4aa4ba2a76
- https://github.com/linebender/xilem/commit/e937723fcb37ff2a37979abba4a723154d11bffc
- https://github.com/linebender/xilem/commit/6058189104d3a18ee3271c6763aa1c9f9ae3758c
- https://github.com/linebender/xilem/commit/424f667a1dd3f32ea08e42a4ff6db1ec3d95e6c7

The support was removed during the switch to Masonry.

Masonry should be changed to include support for non-Winit events, in a way that lets an off-thread executor request to update the widget tree.

Then Xilem should be updated to create that executor and run it in a background thread.

**Comment by DJMcNab** [comment]
This was addressed in https://github.com/linebender/xilem/pull/423!
