### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by liaoxuewei** [linebender/xilem#350]
Follow the instructions to make a simple demo trainer, but there is a compilation error. Is there any information you can provide, thanks!

E:\MyProjects\rust-app>cargo build
    Updating `tuna` index
   Compiling masonry v0.1.2
error[E0609]: no field `app` on type `RefMut<'_, AppRootInner>`
   --> C:\Users\liaoxuewei\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\masonry-0.1.2\src\app_root.rs:217:19
    |
217 |             inner.app.quit();
    |                   ^^^ unknown field

For more information about this error, try `rustc --explain E0609`.
error: could not compile `masonry` due to previous error

**Comment by DJMcNab** [comment]
I don't know that this is actionable at the moment, as we don't have anything which could guide a reproduction. The code in Masonry has changed significantly since then, so I suspect this has probably been fixed.

If you still see this with masonry 0.2, please let us know.
