### ISSUE TITLE
Trim dependencies

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/xilem#371]
Some dependencies can probably be removed with minimal effort to reduce build times / sizes:

- serde
- im
- chrono
- fluent

**Comment by badcodecat** [comment]
Would removing fluent affect automatic re-translation of text in elements as recommended here <https://github.com/projectfluent/fluent/wiki/Good-Practices-for-Developers#prefer-declarative-over-imperative>?
Perhaps this is something not implemented/not planned?

**Comment by PoignardAzur** [comment]
This issue is outdated. All the dependencies listed except serde were removed from masonry, and serde isn't leaving any time soon.

Re: fluent, right now we don't really handle internationalization, and it's not on our roadmap for this year. What little internationalization support there was in Druid was nowhere near the infrastructure needed before the good practices mentioned in your link become relevant.
