### ISSUE TITLE
New Contributor Help

### ISSUE THREAD

**Issue by DasLixou** [linebender/xilem#41]
Hi! I wanna start contribute to xilem and wanted to know if there is a roadmap / board for what needs to be done and what would be easy and generally how to work with this code structure and what the goals of the project are. Also: is there a discord server? I read that there's a zulip thing but i never worked with it and it seems more like another issue tool instead of active communication

**Comment by xStrom** [comment]
No roadmap as of right now, but we plan to make one. Right now we are figuring out some fundamental traits, but things should start becoming more clear in a month or two.

You're on the right track by finding a reference to our Zulip instance. It's not an issue tool, it is a chat application. Unlike Discord it doesn't have voice or video, but it has better text. We have a [Xilem stream](https://xi.zulipchat.com/#narrow/stream/354396-xilem) there, where discussion around project structure and goals happens.
