### ISSUE TITLE
xilem_web: Error running `counter` example: Unable to preventDefault inside passive event listener inovcation

### ISSUE THREAD

**Issue by casey** [linebender/xilem#457]
I was trying out the counter example, and got an error in the console whenever I pressed a button. The error is "Unable to preventDefault inside passive event listener inovcation", screenshot below:

<img width="853" alt="Screenshot 2024-07-28 at 1 07 53 PM" src="https://github.com/user-attachments/assets/770a27b1-7381-4425-bbec-6b2d5ec52a84">

**Comment by Philipp-M** [comment]
#458 should fix this, can you confirm?

**Comment by casey** [comment]
@Philipp-M Yup, can confirm, that fixes it!
