### ISSUE TITLE
Consider renaming `app_logic` to something else

### ISSUE THREAD

**Issue by casey** [linebender/xilem#464]
My personal opinion is that `app_logic` is slightly unclear. "The app logic function" doesn't necessarily imply what it does to me. I think "update" or "view_update" might be clearer.

**Comment by DJMcNab** [comment]
This would be better discussed on [Zulip](https://xi.zulipchat.com/#narrow/stream/354396-xilem). Please make a thread there!

Thank you.

**Comment by casey** [comment]
Sure, will do!
