### ISSUE TITLE
Regression in calc example

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/xilem#490]
Here's what the calc example looks like in main branch right now (commit 99d61603):

![image](https://github.com/user-attachments/assets/25635ac9-9336-4267-8b1d-9a2927813830)

A quick bisect tells me #487 is responsible for the regression.

My system is 64 bit PopOS 22.04.

**Comment by Philipp-M** [comment]
> (We should probably do snapshot tests in examples to avoid this kind of problem.)

You're right that would've probably caught it, the issue is a missing `.flex(1.0)` in `num_row`. #491 should fix it. Wonder why I haven't seen that...
