### ISSUE TITLE
xilem flex: gap should default to 0

### ISSUE THREAD

**Issue by derekdreery** [linebender/xilem#569]
I think that the gap in flex layouts should default to 0 to match flex-box. Currently it's `10.`.

**Comment by DJMcNab** [comment]
I don't agree; our current state has very few styling capabilities, and the default design is intended to be "usable" for e.g. demos. There are very few uses of flex which want all of the items to be shoved against each other.

You should also be able to create your own wrapper around the `flex` component which has a default gap of zero.

**Comment by DJMcNab** [comment]
We decided in office hours to not address this for now.

We do want to make changes here, but it will come as part of a fuller styling change.

**Comment by jaredoconnell** [comment]
In the future, we're probably going to want to address this by expanding the widgets in a way that visually spaces them, but allows them to be interacted with. For example, a button that's too small would be not touch-friendly.

**Comment by TechComet** [comment]
some use 8
