### ISSUE TITLE
Masonry: Reason about `Image` widget layout implementation

### ISSUE THREAD

**Issue by DJMcNab** [linebender/xilem#574]
This is the issue from the TODO comment at:
https://github.com/linebender/xilem/blob/7be4dd2a2f8bf820fc19a3af2a00600d05e4d4c7/masonry/src/widget/image.rs#L94-L97

In particular, the current layout logic entirely ignores the [`FillStrat`](https://github.com/linebender/xilem/blob/7be4dd2a2f8bf820fc19a3af2a00600d05e4d4c7/masonry/src/widget/mod.rs#L62). Effectively, the [`aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) is always `auto`, so the only troublesome case is if we have a minimum/maximum set which never matches the given aspect ratio.

This logic has recently (#571) been changed from the original [Druid version](https://github.com/linebender/druid/blob/4fe393927f8e59baacb53527a665980a157a0ad4/druid/src/widget/image.rs#L194-L202). 

The steps for this issue are:
1) Work out the correct layout logic. It might be that the current version is correct, at least whilst we can't set `aspect-ratio`.
2) Write a few test cases for the layout logic, and integrate them into the tests module. These could probably use screenshot tests.
3) Remove the original TODO comment.

**Comment by DJMcNab** [comment]
See also the [CSS images model](https://drafts.csswg.org/css-images).

[`FillStrat`](https://github.com/linebender/xilem/blob/7be4dd2a2f8bf820fc19a3af2a00600d05e4d4c7/masonry/src/widget/mod.rs#L62) could also probably be renamed. It most closely matches `object-fit` web property, with a couple of extra variants. I don't think the current name accurately describes what is being covered - the "image size" as compared to the layout size aren't really meaningfully different except in very rare cases (primarily because of use of `sized_box`).
Alternatively, it could be removed entirely, to be brought back when we implement more of the CSS images model.

**Comment by failingprovince** [comment]
In my opinion the current logic works, but only covers the `FillStrat::Contain` case.
I would implement a match on `FillStrat`:

```rust
let size = match self.fill {
    FillStrat::Contain => bc.constrain_aspect_ratio(image_size.height / image_size.width, image_size.width),
    // Implement missing arms.
}
```

Also I'd just call `FillStrat` `ObjectFit`.

**Comment by failingprovince** [comment]
Please check out [the new implementation](https://github.com/failingprovince/xilem/commit/6f989442536206a05c24a06664b3638d3301a65d) I wrote.

I'm not so good at testing, do you have any suggestions where to start for this?
Then if everything looks good I'll do a PR.

**Comment by jaredoconnell** [comment]
> Please check out [the new implementation](https://github.com/failingprovince/xilem/commit/6f989442536206a05c24a06664b3638d3301a65d) I wrote.
> 
> I'm not so good at testing, do you have any suggestions where to start for this? Then if everything looks good I'll do a PR.

You can use the tests in the image file and my grid PR as examples: https://github.com/linebender/xilem/pull/570/files#diff-89b46432f5a2ba38b712739a5b75b1c81f698a72b81ac6d07fa7e8117c28836cR309

Create a new test function in the image widget file. For the test cases, create the image widget with each of your constraints in a way that would differentiate it from the default case, and get an image snapshot of it. You can probably use the code-generated images shown in the `edit_image` test.

Write the test code as shown. It will fail when you first run it. Check the screenshots folder; in there you will find the new image with `.new` in the file extension. Confirm that it is correct as rendered. If it is, rename it to remove the `.new`. If it isn't correct, delete it and fix your test.

For the tests to run, you will need to install git lfs.

**Comment by DJMcNab** [comment]
I'd also generally recommend just making a draft PR in this circumstance. It means that discussion of this proposal can be scoped to that proposal.

**Comment by failingprovince** [comment]
> You can use the tests in the image file and my grid PR as examples: https://github.com/linebender/xilem/pull/570/files#diff-89b46432f5a2ba38b712739a5b75b1c81f698a72b81ac6d07fa7e8117c28836cR309
> 
> Create a new test function in the image widget file. For the test cases, create the image widget with each of your constraints in a way that would differentiate it from the default case, and get an image snapshot of it. You can probably use the code-generated images shown in the `edit_image` test.
> 
> Write the test code as shown. It will fail when you first run it. Check the screenshots folder; in there you will find the new image with `.new` in the file extension. Confirm that it is correct as rendered. If it is, rename it to remove the `.new`. If it isn't correct, delete it and fix your test.
Thanks I'll work on it.

> I'd also generally recommend just making a draft PR in this circumstance. It means that discussion of this proposal can be scoped to that proposal.

[Done](https://github.com/linebender/xilem/pull/605)!
