### ISSUE TITLE
Window title not support UTF-8

### ISSUE THREAD

**Issue by TechComet** [linebender/xilem#583]
this example in Arabic
Arabic not displaying in window title
```
use winit::error::EventLoopError;
use xilem::{EventLoop, WidgetView, Xilem};
use xilem::view::flex;

fn app_logic(_: &mut u32) -> impl WidgetView<u32> {
    flex(())
}

fn main() -> Result<(), EventLoopError> {
    let app = Xilem::new(0, app_logic);
    app.run_windowed(EventLoop::with_user_event(), "السلام عليكم".into()).unwrap();
    Ok(())
}

```

**Comment by DJMcNab** [comment]
Can you confirm whether this works for you with raw [winit](https://github.com/rust-windowing/winit) (e.g. by editing one of their examples)?

We do not do any pre-processing of the title before providing it to winit, and so I do not think we can have caused this issue.
We can re-open if for some reason you cannot reproduce just using winit. Thank you.
