### ISSUE TITLE
Is it possible to add the discussions for this repo ?

### ISSUE THREAD

**Issue by ghost** [linebender/xilem#59]

**Comment by xStrom** [comment]
We have chosen Zulip as our discussion platform. Specifically the [Xi Zulip](https://xi.zulipchat.com/) instance and then the **#xilem** stream there.

I see that our current Xilem readme on GitHub doesn't point to there, which is an oversight and will be addressed.

**Comment by curt-wise** [comment]
> I see that our current Xilem readme on GitHub doesn't point to there

Please add a working code example for xilem in the readme as well.

**Comment by waywardmonkeys** [comment]
PR #94 adds a community section and links to Zulip.

**Comment by DJMcNab** [comment]
I'm going to close this one out.
