### ISSUE TITLE
xilem_web svg regression: Missing stroke attribute

### ISSUE THREAD

**Issue by burrbull** [linebender/xilem#716]
Yet another regression after #699 

```rust
Circle::new((0.0, 0.0), 5.0)
            .fill(Color::rgb8(0x99, 0x99, 0x99))
            .stroke(Color::BLACK, Stroke::new(0.5))
```

Before:
![Screenshot_20241026_132228](https://github.com/user-attachments/assets/5e0dc500-0e3e-4050-9c32-7d61cb32b63e)

After:
![Screenshot_20241026_132513](https://github.com/user-attachments/assets/dc4f30d7-bd28-41c3-9b34-1ed2e4ba8607)

**Comment by Philipp-M** [comment]
Thanks for catching this, can you check if #717 fixes this?

**Comment by burrbull** [comment]
Seems like yes.
