### ISSUE TITLE
macos support

### ISSUE THREAD

**Issue by langzime** [linebender/xilem#781]
When I run the calculator example, my computer freezes directly

**Comment by langzime** [comment]
![image](https://github.com/user-attachments/assets/2cd13d3f-23d6-4800-945e-73b181232ac0)

**Comment by langzime** [comment]
![image](https://github.com/user-attachments/assets/671ab8e6-705e-4bee-8757-5866d3c5d70b)

**Comment by DJMcNab** [comment]
Welcome! Thanks for reporting.
I believe that this is a known, but unexplained, issue - see linebender/vello#548. Our suggested fix is to update your macOS to the latest release, which I expect to resolve your issue.

I'm going to close this as not planned, but if you can debug this and find a fix/workaround, we'll happily accept it.
I'll re-open if you report that the hang still happens with an updated macOS.
